/* Write a function doubleSequence that accepts a base and a length as arguments. The
function should return an array representing a sequence that contains "length" elements.
The first element of the sequence is always the "base", the subsequent elements can be
generated by doubling the previous element of the sequence. */

// Your code here
function doubleSequence(base, length){
    let arr= [];
    if(length === 0){
        return arr;
    }
    if(length > 0){
        arr = [base];
        for(let i = 1; i<length; i++){
            arr[i] = arr[i-1] *2
            arr.push(arr[i]);
        }
    }
    return arr;
}


console.log(doubleSequence(7, 3));  // [7, 14, 28]
console.log(doubleSequence(3, 5));  // [3, 6, 12, 24, 48]
console.log(doubleSequence(5, 3));  // [5, 10, 20]
console.log(doubleSequence(5, 4));  // [5, 10, 20, 40]
console.log(doubleSequence(5, 0));  // [ ]
